In [4]:
import requests
import defs
import pandas as pd
import pickle
from tabulate import tabulate

In [5]:
session = requests.Session()

In [6]:
ins_df = pd.read_pickle("instruments.pkl")

In [7]:
ins_df

          name item_type displayName  pipLocation marginRate
0      XAG_EUR     METAL  Silver/EUR           -4       0.10
1      CAD_SGD  CURRENCY     CAD/SGD           -4       0.05
2      XAG_USD     METAL      Silver           -4       0.10
3    UK100_GBP       CFD      UK 100            0       0.05
4      GBP_NZD  CURRENCY     GBP/NZD           -4       0.05
..         ...       ...         ...          ...        ...
117  JP225_USD       CFD   Japan 225            0       0.05
118    XAG_SGD     METAL  Silver/SGD           -4       0.10
119    EUR_GBP  CURRENCY     EUR/GBP           -4     0.0333
120    XAG_HKD     METAL  Silver/HKD           -4        0.1
121    CAD_CHF  CURRENCY     CAD/CHF           -4       0.04

[122 rows x 5 columns]

In [4]:
our_curr = ['EUR', 'USD', 'GBP', 'JPY', 'CHF', 'NZD', 'CAD']

In [5]:
def fetch_candles(pair_name, count, granularity):
    url = f"{defs.OANDA_URL}/instruments/{pair_name}/candles"
    params = dict(
        count = count,
        granularity = granularity,
        price = "MBA"
    )
    response = session.get(url, params = params, headers = defs.SECURE_HEADER)
    return response.status_code, response.json()

In [6]:
def get_price(dictionary,prices,ohlc,candle):
    for price in prices:
        for oh in ohlc:
            dictionary[f"{price}_{oh}"] = candle[price][oh]

In [7]:
def get_candles_df(json_response):
    
    prices = ['mid', 'bid', 'ask']
    ohlc = ['o','h','l','c']
    
    our_data= []
    for candle in json_response['candles']:
        if candle['complete'] == False:
            continue
        new_dict = {}
        new_dict['time'] = candle['time']
        new_dict['volume'] = candle['volume']
        price = get_price(new_dict,prices,ohlc,candle)
        our_data.append(new_dict)
    return pd.DataFrame.from_dict(our_data)

In [8]:
def get_combinations(our_curr):
    for first_idx in range(len(our_curr)):
        first_pair= our_curr[first_idx]
        for second_idx in range(0,len(our_curr)):
            second_pair = our_curr[second_idx]
            if(first_pair==second_pair):
                continue
            else:
                pair = f"{first_pair}_{second_pair}"
                print(pair)

In [9]:
code, res = fetch_candles("EUR_USD", 10, "H1")

In [10]:
df = get_candles_df(res)

In [11]:
df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2021-05-05T06:00:00.000000000Z,4580,1.20122,1.20160,1.19932,1.19998,1.20114,1.20154,1.19925,1.19991,1.20129,1.20166,1.19938,1.20004
1,2021-05-05T07:00:00.000000000Z,5983,1.19998,1.20049,1.19860,1.19944,1.19992,1.20043,1.19853,1.19938,1.20005,1.20055,1.19867,1.19950
2,2021-05-05T08:00:00.000000000Z,4114,1.19946,1.19970,1.19871,1.19968,1.19940,1.19964,1.19864,1.19961,1.19951,1.19976,1.19878,1.19974
3,2021-05-05T09:00:00.000000000Z,2706,1.19966,1.20044,1.19932,1.20038,1.19959,1.20038,1.19925,1.20031,1.19973,1.20050,1.19938,1.20044
4,2021-05-05T10:00:00.000000000Z,4370,1.20038,1.20200,1.20038,1.20162,1.20032,1.20194,1.20032,1.20155,1.20045,1.20205,1.20044,1.20168
5,2021-05-05T11:00:00.000000000Z,3576,1.20162,1.20188,1.20068,1.20094,1.20157,1.20181,1.20062,1.20087,1.20168,1.20194,1.20074,1.20100
6,2021-05-05T12:00:00.000000000Z,6472,1.20092,1.20116,1.19916,1.19970,1.20086,1.20110,1.19909,1.19964,1.20099,1.20123,1.19922,1.19976
7,2021-05-05T13:00:00.000000000Z,6505,1.19969,1.20096,1.19944,1.19980,1.19963,1.20089,1.19938,1.19973,1.19975,1.20102,1.19950,1.19987
8,2021-05-05T14:00:00.000000000Z,6912,1.19983,1.20120,1.19937,1.20042,1.19976,1.20114,1.19931,1.20035,1.19990,1.20125,1.19943,1.20048

In [12]:
def save_file(candles_df, pair, granularity):
    candles_df.to_pickle(f"{pair}_{granularity}.pkl")

In [13]:
def create_data(pair, granularity):
    code, json_data = fetch_candles(pair,4000,granularity)
    if code != 200:
        print(pair,"Error")
        return
    df = get_candles_df(json_data)
    print(df)
    print(f"{pair} loaded {df.shape[0]} candles from {df.time.min()} to {df.time.max()}")
    save_file(df,pair,granularity)

In [14]:
create_data("EUR_USD","H1")

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    2071  1.18236  1.18368  1.18236
1     2020-09-11T01:00:00.000000000Z    2337  1.18351  1.18403  1.18312
2     2020-09-11T02:00:00.000000000Z    1112  1.18333  1.18384  1.18314
3     2020-09-11T03:00:00.000000000Z    1324  1.18332  1.18363  1.18303
4     2020-09-11T04:00:00.000000000Z    1039  1.18339  1.18374  1.18319
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    4370  1.20038  1.20200  1.20038
3995  2021-05-05T11:00:00.000000000Z    3576  1.20162  1.20188  1.20068
3996  2021-05-05T12:00:00.000000000Z    6472  1.20092  1.20116  1.19916
3997  2021-05-05T13:00:00.000000000Z    6505  1.19969  1.20096  1.19944
3998  2021-05-05T14:00:00.000000000Z    6912  1.19983  1.20120  1.19937

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.18350  1.18228  1.18360  1.18228  1.18342  1.18245  1.18377  1.18245
1     1.18334  1.18344  1.18395  1.18305  1.18327  1.18358  1.18411  1.18318
2     1.18334  1.18326  1.18377  1.18307  1.18327  1.18340  1.18391  1.18322
3     1.18340  1.18325  1.18356  1.18296  1.18333  1.18339  1.18371  1.18310
4     1.18354  1.18332  1.18367  1.18312  1.18346  1.18346  1.18381  1.18326
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.20162  1.20032  1.20194  1.20032  1.20155  1.20045  1.20205  1.20044
3995  1.20094  1.20157  1.20181  1.20062  1.20087  1.20168  1.20194  1.20074
3996  1.19970  1.20086  1.20110  1.19909  1.19964  1.20099  1.20123  1.19922
3997  1.19980  1.19963  1.20089  1.19938  1.19973  1.19975  1.20102  1.19950
3998  1.20042  1.19976  1.20114  1.19931  1.20035  1.19990  1.20125  1.19943

        ask_c
0     1.18357
1     1.18341
2     1.18340
3     1.18347
4     1.18362
...       ...
3994  1.20168
3995  1.20100
3996  1.19976
3997  1.19987
3998  1.20048

[3999 rows x 14 columns]
EUR_USD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z

In [15]:
for first_index in range(len(our_curr)):
    first_pair = our_curr[first_index]
    for second_index in range(0,len(our_curr)):
        second_pair = our_curr[second_index]
        if(first_pair == second_pair):
            continue
        else:
            create_data(f"{first_pair}_{second_pair}", "H1")

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    2071  1.18236  1.18368  1.18236
1     2020-09-11T01:00:00.000000000Z    2337  1.18351  1.18403  1.18312
2     2020-09-11T02:00:00.000000000Z    1112  1.18333  1.18384  1.18314
3     2020-09-11T03:00:00.000000000Z    1324  1.18332  1.18363  1.18303
4     2020-09-11T04:00:00.000000000Z    1039  1.18339  1.18374  1.18319
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    4370  1.20038  1.20200  1.20038
3995  2021-05-05T11:00:00.000000000Z    3576  1.20162  1.20188  1.20068
3996  2021-05-05T12:00:00.000000000Z    6472  1.20092  1.20116  1.19916
3997  2021-05-05T13:00:00.000000000Z    6505  1.19969  1.20096  1.19944
3998  2021-05-05T14:00:00.000000000Z    6912  1.19983  1.20120  1.19937

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.18350  1.18228  1.18360  1.18228  1.18342  1.18245  1.18377  1.18245
1     1.18334  1.18344  1.18395  1.18305  1.18327  1.18358  1.18411  1.18318
2     1.18334  1.18326  1.18377  1.18307  1.18327  1.18340  1.18391  1.18322
3     1.18340  1.18325  1.18356  1.18296  1.18333  1.18339  1.18371  1.18310
4     1.18354  1.18332  1.18367  1.18312  1.18346  1.18346  1.18381  1.18326
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.20162  1.20032  1.20194  1.20032  1.20155  1.20045  1.20205  1.20044
3995  1.20094  1.20157  1.20181  1.20062  1.20087  1.20168  1.20194  1.20074
3996  1.19970  1.20086  1.20110  1.19909  1.19964  1.20099  1.20123  1.19922
3997  1.19980  1.19963  1.20089  1.19938  1.19973  1.19975  1.20102  1.19950
3998  1.20042  1.19976  1.20114  1.19931  1.20035  1.19990  1.20125  1.19943

        ask_c
0     1.18357
1     1.18341
2     1.18340
3     1.18347
4     1.18362
...       ...
3994  1.20168
3995  1.20100
3996  1.19976
3997  1.19987
3998  1.20048

[3999 rows x 14 columns]
EUR_USD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     666  0.92316  0.92456  0.92312
1     2020-09-11T01:00:00.000000000Z     490  0.92439  0.92454  0.92360
2     2020-09-11T02:00:00.000000000Z     307  0.92380  0.92398  0.92328
3     2020-09-11T03:00:00.000000000Z     346  0.92335  0.92370  0.92250
4     2020-09-11T04:00:00.000000000Z     379  0.92254  0.92332  0.92230
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     961  0.86392  0.86426  0.86266
3995  2021-05-05T11:00:00.000000000Z     578  0.86376  0.86382  0.86322
3996  2021-05-05T12:00:00.000000000Z    1002  0.86356  0.86368  0.86256
3997  2021-05-05T13:00:00.000000000Z    1018  0.86268  0.86374  0.86268
3998  2021-05-05T14:00:00.000000000Z    1058  0.86318  0.86367  0.86263

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.92442  0.92306  0.92446  0.92302  0.92433  0.92326  0.92467  0.92322
1     0.92378  0.92430  0.92445  0.92351  0.92369  0.92448  0.92462  0.92368
2     0.92333  0.92371  0.92390  0.92319  0.92324  0.92389  0.92406  0.92337
3     0.92252  0.92327  0.92361  0.92240  0.92242  0.92343  0.92378  0.92260
4     0.92324  0.92246  0.92322  0.92221  0.92315  0.92263  0.92342  0.92238
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.86374  0.86386  0.86419  0.86259  0.86367  0.86399  0.86435  0.86272
3995  0.86360  0.86369  0.86375  0.86315  0.86353  0.86384  0.86388  0.86329
3996  0.86270  0.86349  0.86361  0.86249  0.86263  0.86364  0.86375  0.86262
3997  0.86315  0.86261  0.86368  0.86261  0.86303  0.86276  0.86381  0.86276
3998  0.86299  0.86306  0.86361  0.86256  0.86293  0.86330  0.86373  0.86269

        ask_c
0     0.92450
1     0.92386
2     0.92342
3     0.92262
4     0.92332
...       ...
3994  0.86382
3995  0.86366
3996  0.86278
3997  0.86327
3998  0.86305

[3999 rows x 14 columns]
EUR_GBP loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-10T23:00:00.000000000Z     285  125.574  125.578  125.499
1     2020-09-11T00:00:00.000000000Z     731  125.508  125.623  125.502
2     2020-09-11T01:00:00.000000000Z     669  125.605  125.747  125.605
3     2020-09-11T02:00:00.000000000Z     295  125.651  125.685  125.628
4     2020-09-11T03:00:00.000000000Z     307  125.662  125.662  125.584
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     736  131.258  131.388  131.247
3995  2021-05-05T11:00:00.000000000Z     501  131.348  131.354  131.277
3996  2021-05-05T12:00:00.000000000Z    1148  131.306  131.324  131.133
3997  2021-05-05T13:00:00.000000000Z    1124  131.154  131.238  131.054
3998  2021-05-05T14:00:00.000000000Z    1199  131.088  131.192  131.026

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     125.506  125.566  125.569  125.490  125.496  125.583  125.587  125.508
1     125.608  125.499  125.615  125.494  125.600  125.518  125.631  125.511
2     125.648  125.596  125.738  125.596  125.640  125.614  125.756  125.614
3     125.659  125.642  125.677  125.621  125.648  125.660  125.693  125.635
4     125.644  125.654  125.654  125.575  125.635  125.670  125.670  125.594
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  131.344  131.248  131.380  131.238  131.336  131.267  131.396  131.256
3995  131.302  131.340  131.346  131.268  131.296  131.355  131.363  131.286
3996  131.157  131.299  131.317  131.125  131.149  131.313  131.332  131.141
3997  131.090  131.146  131.231  131.046  131.077  131.161  131.245  131.061
3998  131.102  131.074  131.184  131.019  131.094  131.101  131.199  131.033

        ask_c
0     125.515
1     125.616
2     125.656
3     125.670
4     125.654
...       ...
3994  131.351
3995  131.309
3996  131.165
3997  131.104
3998  131.111

[3999 rows x 14 columns]
EUR_JPY loaded 3999 candles from 2020-09-10T23:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     274  1.07632  1.07685  1.07632
1     2020-09-11T01:00:00.000000000Z     301  1.07684  1.07720  1.07662
2     2020-09-11T02:00:00.000000000Z     138  1.07700  1.07708  1.07682
3     2020-09-11T03:00:00.000000000Z     167  1.07686  1.07696  1.07654
4     2020-09-11T04:00:00.000000000Z     110  1.07664  1.07688  1.07655
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     853  1.09845  1.09876  1.09787
3995  2021-05-05T11:00:00.000000000Z     550  1.09794  1.09794  1.09665
3996  2021-05-05T12:00:00.000000000Z     904  1.09667  1.09688  1.09570
3997  2021-05-05T13:00:00.000000000Z    1104  1.09594  1.09648  1.09530
3998  2021-05-05T14:00:00.000000000Z    1316  1.09594  1.09641  1.09555

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.07682  1.07620  1.07673  1.07620  1.07670  1.07644  1.07697  1.07644
1     1.07698  1.07673  1.07709  1.07651  1.07687  1.07696  1.07732  1.07672
2     1.07684  1.07690  1.07697  1.07670  1.07673  1.07711  1.07719  1.07691
3     1.07666  1.07676  1.07686  1.07643  1.07656  1.07697  1.07707  1.07665
4     1.07680  1.07652  1.07678  1.07644  1.07669  1.07675  1.07697  1.07665
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.09796  1.09837  1.09868  1.09780  1.09788  1.09853  1.09883  1.09794
3995  1.09665  1.09785  1.09785  1.09658  1.09659  1.09803  1.09803  1.09671
3996  1.09592  1.09660  1.09682  1.09563  1.09584  1.09674  1.09695  1.09577
3997  1.09592  1.09588  1.09640  1.09523  1.09575  1.09600  1.09655  1.09537
3998  1.09620  1.09576  1.09634  1.09547  1.09613  1.09612  1.09648  1.09562

        ask_c
0     1.07694
1     1.07709
2     1.07695
3     1.07676
4     1.07691
...       ...
3994  1.09804
3995  1.09671
3996  1.09600
3997  1.09609
3998  1.09628

[3999 rows x 14 columns]
EUR_CHF loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    8525  1.77898  1.77960  1.77634
1     2020-09-11T01:00:00.000000000Z    7738  1.77804  1.77848  1.77672
2     2020-09-11T02:00:00.000000000Z    4339  1.77788  1.77817  1.77692
3     2020-09-11T03:00:00.000000000Z    4672  1.77735  1.77763  1.77608
4     2020-09-11T04:00:00.000000000Z    4103  1.77654  1.77664  1.77534
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z   10626  1.67354  1.67442  1.67080
3995  2021-05-05T11:00:00.000000000Z    8313  1.67131  1.67154  1.66972
3996  2021-05-05T12:00:00.000000000Z   13946  1.67054  1.67067  1.66676
3997  2021-05-05T13:00:00.000000000Z   14417  1.66684  1.66904  1.66464
3998  2021-05-05T14:00:00.000000000Z   16969  1.66574  1.66804  1.66380

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.77804  1.77878  1.77942  1.77615  1.77786  1.77917  1.77981  1.77653
1     1.77789  1.77788  1.77831  1.77650  1.77771  1.77819  1.77866  1.77691
2     1.77736  1.77771  1.77799  1.77676  1.77720  1.77805  1.77835  1.77709
3     1.77657  1.77721  1.77746  1.77591  1.77638  1.77749  1.77781  1.77623
4     1.77604  1.77636  1.77646  1.77511  1.77586  1.77672  1.77683  1.77554
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.67134  1.67336  1.67428  1.67059  1.67117  1.67372  1.67456  1.67096
3995  1.67054  1.67116  1.67140  1.66956  1.67040  1.67146  1.67169  1.66985
3996  1.66686  1.67042  1.67053  1.66660  1.66670  1.67067  1.67083  1.66691
3997  1.66574  1.66668  1.66891  1.66448  1.66550  1.66701  1.66923  1.66479
3998  1.66411  1.66548  1.66790  1.66365  1.66397  1.66599  1.66817  1.66395

        ask_c
0     1.77821
1     1.77807
2     1.77751
3     1.77676
4     1.77622
...       ...
3994  1.67150
3995  1.67067
3996  1.66701
3997  1.66599
3998  1.66425

[3999 rows x 14 columns]
EUR_NZD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    7615  1.55949  1.56063  1.55944
1     2020-09-11T01:00:00.000000000Z    7250  1.56053  1.56096  1.55944
2     2020-09-11T02:00:00.000000000Z    4667  1.55946  1.55974  1.55925
3     2020-09-11T03:00:00.000000000Z    4048  1.55938  1.55966  1.55902
4     2020-09-11T04:00:00.000000000Z    2944  1.55910  1.55928  1.55878
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    8027  1.47468  1.47558  1.47423
3995  2021-05-05T11:00:00.000000000Z    6740  1.47484  1.47498  1.47374
3996  2021-05-05T12:00:00.000000000Z   12192  1.47400  1.47409  1.47222
3997  2021-05-05T13:00:00.000000000Z   12319  1.47294  1.47454  1.47214
3998  2021-05-05T14:00:00.000000000Z   14309  1.47312  1.47364  1.47102

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.56054  1.55935  1.56050  1.55929  1.56041  1.55963  1.56077  1.55955
1     1.55946  1.56039  1.56085  1.55930  1.55934  1.56067  1.56113  1.55957
2     1.55940  1.55932  1.55961  1.55912  1.55930  1.55959  1.55988  1.55936
3     1.55910  1.55926  1.55954  1.55890  1.55898  1.55949  1.55978  1.55911
4     1.55917  1.55897  1.55917  1.55866  1.55906  1.55922  1.55940  1.55890
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.47484  1.47459  1.47548  1.47413  1.47474  1.47477  1.47569  1.47432
3995  1.47400  1.47475  1.47490  1.47365  1.47391  1.47494  1.47507  1.47382
3996  1.47294  1.47390  1.47400  1.47210  1.47285  1.47409  1.47418  1.47233
3997  1.47314  1.47284  1.47446  1.47202  1.47301  1.47304  1.47464  1.47225
3998  1.47133  1.47301  1.47356  1.47092  1.47123  1.47324  1.47374  1.47112

        ask_c
0     1.56067
1     1.55958
2     1.55950
3     1.55922
4     1.55928
...       ...
3994  1.47495
3995  1.47408
3996  1.47304
3997  1.47326
3998  1.47143

[3999 rows x 14 columns]
EUR_CAD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
USD_EUR Error
USD_GBP Error
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T01:00:00.000000000Z    2651  106.133  106.209  106.125
1     2020-09-11T02:00:00.000000000Z    1488  106.180  106.194  106.140
2     2020-09-11T03:00:00.000000000Z    1858  106.192  106.192  106.140
3     2020-09-11T04:00:00.000000000Z    1886  106.170  106.192  106.150
4     2020-09-11T05:00:00.000000000Z    1414  106.168  106.188  106.155
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    2338  109.348  109.368  109.276
3995  2021-05-05T11:00:00.000000000Z    1840  109.304  109.358  109.254
3996  2021-05-05T12:00:00.000000000Z    4789  109.332  109.390  109.243
3997  2021-05-05T13:00:00.000000000Z    5239  109.322  109.334  109.144
3998  2021-05-05T14:00:00.000000000Z    5489  109.261  109.322  109.160

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     106.182  106.127  106.202  106.119  106.176  106.139  106.216  106.131
1     106.192  106.174  106.187  106.134  106.184  106.187  106.200  106.147
2     106.172  106.186  106.186  106.133  106.165  106.199  106.199  106.146
3     106.166  106.163  106.186  106.143  106.161  106.177  106.199  106.157
4     106.184  106.161  106.182  106.148  106.177  106.174  106.195  106.162
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  109.305  109.342  109.361  109.270  109.298  109.355  109.375  109.281
3995  109.334  109.297  109.351  109.247  109.328  109.310  109.364  109.261
3996  109.324  109.325  109.384  109.236  109.317  109.338  109.396  109.250
3997  109.263  109.316  109.327  109.137  109.255  109.328  109.340  109.150
3998  109.212  109.251  109.316  109.154  109.205  109.271  109.328  109.167

        ask_c
0     106.188
1     106.199
2     106.178
3     106.172
4     106.192
...       ...
3994  109.312
3995  109.340
3996  109.330
3997  109.271
3998  109.219

[3999 rows x 14 columns]
USD_JPY loaded 3999 candles from 2020-09-11T01:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     173  0.91027  0.91027  0.90956
1     2020-09-11T01:00:00.000000000Z     179  0.90986  0.91014  0.90955
2     2020-09-11T02:00:00.000000000Z      88  0.91010  0.91018  0.90968
3     2020-09-11T03:00:00.000000000Z      68  0.91004  0.91010  0.90968
4     2020-09-11T04:00:00.000000000Z      67  0.90984  0.90997  0.90966
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     421  0.91507  0.91507  0.91366
3995  2021-05-05T11:00:00.000000000Z     230  0.91368  0.91368  0.91274
3996  2021-05-05T12:00:00.000000000Z     511  0.91312  0.91416  0.91294
3997  2021-05-05T13:00:00.000000000Z     886  0.91352  0.91376  0.91225
3998  2021-05-05T14:00:00.000000000Z     921  0.91340  0.91378  0.91214

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.90990  0.91017  0.91017  0.90946  0.90981  0.91037  0.91037  0.90966
1     0.91014  0.90975  0.91006  0.90947  0.91006  0.90996  0.91022  0.90963
2     0.91000  0.90998  0.91010  0.90960  0.90992  0.91022  0.91026  0.90977
3     0.90980  0.90995  0.91001  0.90960  0.90972  0.91012  0.91018  0.90975
4     0.90983  0.90975  0.90989  0.90957  0.90976  0.90993  0.91005  0.90975
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.91372  0.91500  0.91500  0.91360  0.91365  0.91514  0.91514  0.91373
3995  0.91316  0.91362  0.91362  0.91267  0.91309  0.91374  0.91376  0.91282
3996  0.91348  0.91305  0.91409  0.91285  0.91342  0.91319  0.91424  0.91304
3997  0.91344  0.91345  0.91367  0.91218  0.91327  0.91358  0.91384  0.91232
3998  0.91318  0.91327  0.91372  0.91206  0.91311  0.91353  0.91385  0.91221

        ask_c
0     0.90998
1     0.91021
2     0.91009
3     0.90989
4     0.90990
...       ...
3994  0.91379
3995  0.91322
3996  0.91354
3997  0.91360
3998  0.91324

[3999 rows x 14 columns]
USD_CHF loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
USD_NZD Error

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    1000  1.31898  1.31950  1.31804
1     2020-09-11T01:00:00.000000000Z     811  1.31858  1.31870  1.31756
2     2020-09-11T02:00:00.000000000Z     412  1.31786  1.31799  1.31730
3     2020-09-11T03:00:00.000000000Z     396  1.31783  1.31808  1.31745
4     2020-09-11T04:00:00.000000000Z     311  1.31750  1.31759  1.31722
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     700  1.22851  1.22864  1.22686
3995  2021-05-05T11:00:00.000000000Z     648  1.22740  1.22772  1.22692
3996  2021-05-05T12:00:00.000000000Z    1269  1.22735  1.22822  1.22668
3997  2021-05-05T13:00:00.000000000Z    1490  1.22772  1.22829  1.22680
3998  2021-05-05T14:00:00.000000000Z    2123  1.22782  1.22832  1.22535

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.31860  1.31887  1.31939  1.31794  1.31850  1.31908  1.31961  1.31815
1     1.31784  1.31848  1.31860  1.31745  1.31774  1.31867  1.31879  1.31767
2     1.31780  1.31776  1.31790  1.31721  1.31770  1.31797  1.31809  1.31738
3     1.31748  1.31773  1.31799  1.31735  1.31739  1.31793  1.31816  1.31754
4     1.31737  1.31741  1.31750  1.31713  1.31728  1.31758  1.31768  1.31730
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.22738  1.22842  1.22856  1.22677  1.22730  1.22860  1.22872  1.22694
3995  1.22738  1.22732  1.22765  1.22684  1.22729  1.22749  1.22780  1.22699
3996  1.22774  1.22727  1.22812  1.22659  1.22767  1.22743  1.22831  1.22676
3997  1.22786  1.22765  1.22820  1.22673  1.22777  1.22780  1.22838  1.22688
3998  1.22569  1.22774  1.22824  1.22527  1.22560  1.22791  1.22840  1.22543

        ask_c
0     1.31870
1     1.31795
2     1.31790
3     1.31756
4     1.31746
...       ...
3994  1.22746
3995  1.22746
3996  1.22782
3997  1.22794
3998  1.22578

[3999 rows x 14 columns]
USD_CAD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
GBP_EUR Error
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    1446  1.28072  1.28120  1.27947
1     2020-09-11T01:00:00.000000000Z    1275  1.28031  1.28128  1.27997
2     2020-09-11T02:00:00.000000000Z     748  1.28092  1.28209  1.28072
3     2020-09-11T03:00:00.000000000Z     707  1.28158  1.28282  1.28105
4     2020-09-11T04:00:00.000000000Z     686  1.28278  1.28308  1.28186
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    1421  1.38950  1.39264  1.38942
3995  2021-05-05T11:00:00.000000000Z     820  1.39124  1.39188  1.39064
3996  2021-05-05T12:00:00.000000000Z    1974  1.39066  1.39243  1.38940
3997  2021-05-05T13:00:00.000000000Z    1983  1.39066  1.39134  1.38935
3998  2021-05-05T14:00:00.000000000Z    2142  1.38998  1.39214  1.38906

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.28028  1.28061  1.28109  1.27935  1.28020  1.28084  1.28130  1.27958
1     1.28095  1.28021  1.28119  1.27986  1.28085  1.28041  1.28136  1.28008
2     1.28160  1.28083  1.28200  1.28061  1.28152  1.28102  1.28218  1.28081
3     1.28280  1.28150  1.28273  1.28095  1.28271  1.28166  1.28291  1.28115
4     1.28198  1.28268  1.28299  1.28178  1.28188  1.28287  1.28318  1.28195
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.39121  1.38943  1.39257  1.38933  1.39114  1.38958  1.39272  1.38951
3995  1.39064  1.39117  1.39180  1.39058  1.39058  1.39131  1.39195  1.39070
3996  1.39063  1.39058  1.39236  1.38933  1.39057  1.39074  1.39250  1.38947
3997  1.38994  1.39060  1.39126  1.38929  1.38982  1.39072  1.39141  1.38941
3998  1.39102  1.38989  1.39207  1.38899  1.39094  1.39006  1.39220  1.38912

        ask_c
0     1.28037
1     1.28105
2     1.28168
3     1.28289
4     1.28207
...       ...
3994  1.39128
3995  1.39070
3996  1.39069
3997  1.39006
3998  1.39110

[3999 rows x 14 columns]
GBP_USD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    2113  135.948  135.986  135.776
1     2020-09-11T01:00:00.000000000Z    1807  135.884  136.048  135.872
2     2020-09-11T02:00:00.000000000Z    1017  136.012  136.098  135.984
3     2020-09-11T03:00:00.000000000Z    1061  136.096  136.202  136.004
4     2020-09-11T04:00:00.000000000Z    1113  136.193  136.238  136.082
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    2326  151.936  152.212  151.914
3995  2021-05-05T11:00:00.000000000Z    1449  152.066  152.127  152.044
3996  2021-05-05T12:00:00.000000000Z    3835  152.046  152.208  151.940
3997  2021-05-05T13:00:00.000000000Z    3423  152.026  152.053  151.781
3998  2021-05-05T14:00:00.000000000Z    4011  151.870  152.009  151.784

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     135.882  135.935  135.972  135.762  135.869  135.961  135.999  135.791
1     136.014  135.871  136.032  135.858  135.999  135.897  136.063  135.885
2     136.094  135.998  136.084  135.970  136.079  136.026  136.112  135.997
3     136.195  136.082  136.189  135.990  136.181  136.109  136.214  136.017
4     136.102  136.178  136.225  136.067  136.090  136.208  136.250  136.095
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  152.068  151.925  152.201  151.902  152.058  151.947  152.222  151.925
3995  152.044  152.056  152.116  152.032  152.033  152.075  152.138  152.054
3996  152.028  152.036  152.199  151.929  152.018  152.056  152.217  151.950
3997  151.872  152.015  152.042  151.769  151.851  152.038  152.064  151.793
3998  151.914  151.854  151.996  151.772  151.902  151.886  152.022  151.795

        ask_c
0     135.895
1     136.030
2     136.108
3     136.209
4     136.115
...       ...
3994  152.077
3995  152.054
3996  152.039
3997  151.894
3998  151.925

[3999 rows x 14 columns]
GBP_JPY loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    3763  1.16584  1.16601  1.16438
1     2020-09-11T01:00:00.000000000Z    3543  1.16491  1.16613  1.16470
2     2020-09-11T02:00:00.000000000Z    2139  1.16580  1.16644  1.16558
3     2020-09-11T03:00:00.000000000Z    2116  1.16626  1.16712  1.16583
4     2020-09-11T04:00:00.000000000Z    1976  1.16707  1.16729  1.16620
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    6364  1.27152  1.27348  1.27091
3995  2021-05-05T11:00:00.000000000Z    2272  1.27119  1.27158  1.26982
3996  2021-05-05T12:00:00.000000000Z    7877  1.26986  1.27159  1.26976
3997  2021-05-05T13:00:00.000000000Z    8863  1.27038  1.27047  1.26864
3998  2021-05-05T14:00:00.000000000Z    9855  1.26964  1.27064  1.26866

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.16490  1.16566  1.16586  1.16424  1.16476  1.16602  1.16617  1.16452
1     1.16582  1.16476  1.16600  1.16455  1.16569  1.16506  1.16632  1.16483
2     1.16624  1.16568  1.16631  1.16543  1.16611  1.16593  1.16657  1.16571
3     1.16708  1.16613  1.16700  1.16566  1.16695  1.16639  1.16725  1.16598
4     1.16635  1.16694  1.16716  1.16606  1.16621  1.16720  1.16743  1.16633
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.27120  1.27141  1.27338  1.27082  1.27110  1.27162  1.27358  1.27100
3995  1.26983  1.27110  1.27149  1.26973  1.26973  1.27128  1.27167  1.26992
3996  1.27034  1.26976  1.27149  1.26966  1.27024  1.26997  1.27169  1.26985
3997  1.26964  1.27027  1.27037  1.26855  1.26936  1.27048  1.27057  1.26873
3998  1.27023  1.26937  1.27054  1.26855  1.27014  1.26991  1.27075  1.26877

        ask_c
0     1.16505
1     1.16596
2     1.16638
3     1.16722
4     1.16649
...       ...
3994  1.27129
3995  1.26993
3996  1.27044
3997  1.26992
3998  1.27032

[3999 rows x 14 columns]
GBP_CHF loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    9611  1.92700  1.92700  1.92265
1     2020-09-11T01:00:00.000000000Z    8321  1.92346  1.92499  1.92245
2     2020-09-11T02:00:00.000000000Z    4939  1.92454  1.92520  1.92378
3     2020-09-11T03:00:00.000000000Z    5081  1.92493  1.92586  1.92419
4     2020-09-11T04:00:00.000000000Z    4912  1.92574  1.92586  1.92316
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z   11573  1.93717  1.93836  1.93458
3995  2021-05-05T11:00:00.000000000Z    8126  1.93504  1.93580  1.93372
3996  2021-05-05T12:00:00.000000000Z   13896  1.93442  1.93516  1.93172
3997  2021-05-05T13:00:00.000000000Z   15894  1.93209  1.93349  1.92804
3998  2021-05-05T14:00:00.000000000Z   17301  1.92972  1.93168  1.92790

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.92345  1.92663  1.92663  1.92229  1.92319  1.92737  1.92737  1.92298
1     1.92456  1.92321  1.92471  1.92211  1.92422  1.92372  1.92528  1.92278
2     1.92491  1.92421  1.92495  1.92348  1.92461  1.92488  1.92547  1.92403
3     1.92576  1.92464  1.92558  1.92392  1.92545  1.92522  1.92619  1.92442
4     1.92374  1.92544  1.92559  1.92286  1.92351  1.92605  1.92613  1.92347
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.93500  1.93698  1.93818  1.93441  1.93483  1.93736  1.93857  1.93476
3995  1.93443  1.93486  1.93562  1.93351  1.93429  1.93523  1.93599  1.93390
3996  1.93209  1.93427  1.93500  1.93152  1.93191  1.93458  1.93535  1.93190
3997  1.92968  1.93193  1.93331  1.92785  1.92923  1.93225  1.93367  1.92824
3998  1.92831  1.92930  1.93148  1.92771  1.92814  1.93014  1.93188  1.92808

        ask_c
0     1.92371
1     1.92490
2     1.92521
3     1.92608
4     1.92398
...       ...
3994  1.93518
3995  1.93457
3996  1.93227
3997  1.93013
3998  1.92848

[3999 rows x 14 columns]
GBP_NZD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    8662  1.68921  1.68942  1.68761
1     2020-09-11T01:00:00.000000000Z    7088  1.68818  1.68854  1.68746
2     2020-09-11T02:00:00.000000000Z    5547  1.68806  1.68914  1.68793
3     2020-09-11T03:00:00.000000000Z    4955  1.68888  1.69006  1.68840
4     2020-09-11T04:00:00.000000000Z    4589  1.69003  1.69028  1.68859
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    9968  1.70698  1.70955  1.70690
3995  2021-05-05T11:00:00.000000000Z    6594  1.70758  1.70868  1.70681
3996  2021-05-05T12:00:00.000000000Z   12184  1.70682  1.70833  1.70612
3997  2021-05-05T13:00:00.000000000Z   13961  1.70736  1.70824  1.70513
3998  2021-05-05T14:00:00.000000000Z   15900  1.70664  1.70720  1.70468

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     1.68816  1.68899  1.68924  1.68743  1.68798  1.68943  1.68967  1.68779
1     1.68808  1.68799  1.68836  1.68727  1.68790  1.68837  1.68872  1.68763
2     1.68887  1.68788  1.68895  1.68775  1.68873  1.68824  1.68933  1.68810
3     1.69004  1.68873  1.68987  1.68821  1.68982  1.68903  1.69026  1.68858
4     1.68882  1.68981  1.69012  1.68841  1.68865  1.69025  1.69047  1.68875
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  1.70756  1.70686  1.70942  1.70677  1.70743  1.70710  1.70968  1.70700
3995  1.70681  1.70744  1.70856  1.70667  1.70669  1.70773  1.70881  1.70693
3996  1.70736  1.70669  1.70821  1.70597  1.70727  1.70695  1.70850  1.70626
3997  1.70659  1.70726  1.70813  1.70499  1.70641  1.70746  1.70836  1.70525
3998  1.70492  1.70646  1.70712  1.70457  1.70481  1.70681  1.70730  1.70479

        ask_c
0     1.68833
1     1.68827
2     1.68901
3     1.69025
4     1.68900
...       ...
3994  1.70768
3995  1.70693
3996  1.70746
3997  1.70677
3998  1.70504

[3999 rows x 14 columns]
GBP_CAD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
JPY_EUR Error
JPY_USD Error
JPY_GBP Error
JPY_CHF Error
JPY_NZD Error
JPY_CAD Error
CHF_EUR Error
CHF_USD Error
CHF_GBP Error
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    3485  116.608  116.692  116.592
1     2020-09-11T01:00:00.000000000Z    3227  116.646  116.754  116.633
2     2020-09-11T02:00:00.000000000Z    1711  116.666  116.700  116.653
3     2020-09-11T03:00:00.000000000Z    1730  116.694  116.701  116.646
4     2020-09-11T04:00:00.000000000Z    1709  116.698  116.726  116.671
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    3859  119.493  119.650  119.480
3995  2021-05-05T11:00:00.000000000Z    2510  119.628  119.752  119.583
3996  2021-05-05T12:00:00.000000000Z    6051  119.736  119.748  119.598
3997  2021-05-05T13:00:00.000000000Z    7203  119.674  119.765  119.573
3998  2021-05-05T14:00:00.000000000Z    7805  119.618  119.731  119.566

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     116.646  116.596  116.665  116.572  116.636  116.620  116.727  116.604
1     116.666  116.634  116.736  116.620  116.651  116.657  116.771  116.645
2     116.694  116.651  116.691  116.642  116.681  116.681  116.712  116.664
3     116.697  116.682  116.691  116.636  116.687  116.705  116.713  116.656
4     116.689  116.686  116.716  116.660  116.677  116.709  116.737  116.681
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  119.628  119.484  119.640  119.470  119.619  119.502  119.659  119.490
3995  119.734  119.619  119.742  119.572  119.723  119.637  119.761  119.594
3996  119.677  119.726  119.739  119.587  119.667  119.746  119.758  119.609
3997  119.620  119.664  119.754  119.563  119.602  119.683  119.776  119.583
3998  119.595  119.601  119.722  119.554  119.584  119.636  119.742  119.576

        ask_c
0     116.657
1     116.682
2     116.706
3     116.707
4     116.701
...       ...
3994  119.638
3995  119.745
3996  119.687
3997  119.639
3998  119.606

[3999 rows x 14 columns]
CHF_JPY loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
CHF_NZD Error
CHF_CAD Error
NZD_EUR Error
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     872  0.66464  0.66615  0.66454
1     2020-09-11T01:00:00.000000000Z     614  0.66564  0.66619  0.66534
2     2020-09-11T02:00:00.000000000Z     310  0.66560  0.66615  0.66552
3     2020-09-11T03:00:00.000000000Z     314  0.66580  0.66628  0.66562
4     2020-09-11T04:00:00.000000000Z     338  0.66611  0.66666  0.66609
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     867  0.71730  0.71926  0.71727
3995  2021-05-05T11:00:00.000000000Z     551  0.71895  0.71964  0.71884
3996  2021-05-05T12:00:00.000000000Z    1355  0.71892  0.71988  0.71854
3997  2021-05-05T13:00:00.000000000Z    1519  0.71972  0.72066  0.71915
3998  2021-05-05T14:00:00.000000000Z    1821  0.72030  0.72178  0.71934

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.66562  0.66457  0.66606  0.66447  0.66554  0.66472  0.66624  0.66462
1     0.66558  0.66556  0.66611  0.66525  0.66550  0.66572  0.66627  0.66542
2     0.66578  0.66553  0.66606  0.66544  0.66570  0.66568  0.66624  0.66560
3     0.66613  0.66573  0.66620  0.66555  0.66607  0.66586  0.66635  0.66569
4     0.66641  0.66603  0.66658  0.66602  0.66633  0.66619  0.66673  0.66616
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.71897  0.71721  0.71917  0.71719  0.71889  0.71738  0.71934  0.71735
3995  0.71890  0.71887  0.71957  0.71877  0.71883  0.71903  0.71972  0.71892
3996  0.71974  0.71885  0.71981  0.71845  0.71967  0.71899  0.71997  0.71863
3997  0.72026  0.71964  0.72059  0.71908  0.72016  0.71979  0.72073  0.71922
3998  0.72136  0.72022  0.72170  0.71926  0.72129  0.72037  0.72185  0.71941

        ask_c
0     0.66570
1     0.66565
2     0.66585
3     0.66619
4     0.66649
...       ...
3994  0.71905
3995  0.71897
3996  0.71981
3997  0.72035
3998  0.72143

[3999 rows x 14 columns]
NZD_USD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
NZD_GBP Error

                                time  volume   mid_o   mid_h   mid_l   mid_c  \
0     2020-09-11T01:00:00.000000000Z    3353  70.646  70.742  70.638  70.674
1     2020-09-11T02:00:00.000000000Z    1776  70.672  70.724  70.665  70.700
2     2020-09-11T03:00:00.000000000Z    1940  70.701  70.732  70.660  70.723
3     2020-09-11T04:00:00.000000000Z    1875  70.722  70.778  70.719  70.750
4     2020-09-11T05:00:00.000000000Z    1280  70.747  70.775  70.720  70.774
...                              ...     ...     ...     ...     ...     ...
3994  2021-05-05T10:00:00.000000000Z    4720  78.433  78.622  78.426  78.586
3995  2021-05-05T11:00:00.000000000Z    3363  78.584  78.650  78.560  78.600
3996  2021-05-05T12:00:00.000000000Z    7266  78.598  78.690  78.572  78.685
3997  2021-05-05T13:00:00.000000000Z    8604  78.684  78.740  78.566  78.700
3998  2021-05-05T14:00:00.000000000Z    9959  78.700  78.800  78.603  78.782

       bid_o   bid_h   bid_l   bid_c   ask_o   ask_h   ask_l   ask_c
0     70.636  70.732  70.629  70.663  70.655  70.752  70.648  70.684
1     70.661  70.717  70.655  70.690  70.683  70.733  70.675  70.710
2     70.692  70.723  70.649  70.714  70.710  70.742  70.670  70.732
3     70.712  70.769  70.709  70.740  70.732  70.788  70.729  70.759
4     70.737  70.766  70.711  70.764  70.757  70.784  70.730  70.783
...      ...     ...     ...     ...     ...     ...     ...     ...
3994  78.424  78.614  78.417  78.577  78.442  78.631  78.436  78.594
3995  78.575  78.642  78.551  78.593  78.593  78.658  78.568  78.608
3996  78.591  78.681  78.564  78.676  78.606  78.699  78.581  78.694
3997  78.676  78.732  78.558  78.681  78.693  78.748  78.574  78.718
3998  78.682  78.793  78.594  78.774  78.718  78.810  78.611  78.790

[3999 rows x 14 columns]
NZD_JPY loaded 3999 candles from 2020-09-11T01:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     897  0.60502  0.60604  0.60488
1     2020-09-11T01:00:00.000000000Z     679  0.60566  0.60616  0.60539
2     2020-09-11T02:00:00.000000000Z     327  0.60579  0.60608  0.60570
3     2020-09-11T03:00:00.000000000Z     307  0.60585  0.60617  0.60568
4     2020-09-11T04:00:00.000000000Z     353  0.60603  0.60652  0.60600
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    1128  0.65640  0.65739  0.65608
3995  2021-05-05T11:00:00.000000000Z     668  0.65691  0.65708  0.65643
3996  2021-05-05T12:00:00.000000000Z    1625  0.65644  0.65747  0.65642
3997  2021-05-05T13:00:00.000000000Z    2036  0.65750  0.65840  0.65671
3998  2021-05-05T14:00:00.000000000Z    2356  0.65788  0.65898  0.65698

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.60564  0.60490  0.60590  0.60476  0.60551  0.60515  0.60619  0.60501
1     0.60576  0.60553  0.60602  0.60527  0.60564  0.60579  0.60631  0.60551
2     0.60588  0.60567  0.60596  0.60557  0.60575  0.60591  0.60621  0.60583
3     0.60604  0.60571  0.60605  0.60555  0.60593  0.60599  0.60629  0.60581
4     0.60632  0.60590  0.60640  0.60588  0.60620  0.60616  0.60664  0.60612
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.65694  0.65627  0.65725  0.65596  0.65681  0.65654  0.65753  0.65621
3995  0.65648  0.65679  0.65696  0.65631  0.65637  0.65703  0.65721  0.65655
3996  0.65747  0.65633  0.65736  0.65630  0.65736  0.65656  0.65759  0.65654
3997  0.65791  0.65738  0.65828  0.65658  0.65770  0.65761  0.65851  0.65684
3998  0.65872  0.65770  0.65885  0.65686  0.65861  0.65807  0.65911  0.65709

        ask_c
0     0.60577
1     0.60588
2     0.60600
3     0.60616
4     0.60644
...       ...
3994  0.65706
3995  0.65660
3996  0.65758
3997  0.65812
3998  0.65884

[3999 rows x 14 columns]
NZD_CHF loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z    5058  0.87663  0.87804  0.87663
1     2020-09-11T01:00:00.000000000Z    4482  0.87766  0.87802  0.87705
2     2020-09-11T02:00:00.000000000Z    2847  0.87713  0.87760  0.87712
3     2020-09-11T03:00:00.000000000Z    2638  0.87738  0.87780  0.87726
4     2020-09-11T04:00:00.000000000Z    2351  0.87760  0.87818  0.87756
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z    5673  0.88120  0.88270  0.88120
3995  2021-05-05T11:00:00.000000000Z    4873  0.88244  0.88326  0.88226
3996  2021-05-05T12:00:00.000000000Z    8782  0.88234  0.88370  0.88208
3997  2021-05-05T13:00:00.000000000Z    9576  0.88366  0.88448  0.88318
3998  2021-05-05T14:00:00.000000000Z   12180  0.88436  0.88456  0.88262

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.87768  0.87649  0.87793  0.87649  0.87757  0.87677  0.87815  0.87677
1     0.87713  0.87754  0.87792  0.87692  0.87700  0.87779  0.87817  0.87716
2     0.87738  0.87701  0.87750  0.87700  0.87727  0.87725  0.87776  0.87725
3     0.87760  0.87728  0.87770  0.87713  0.87746  0.87749  0.87794  0.87738
4     0.87788  0.87745  0.87807  0.87742  0.87776  0.87775  0.87832  0.87766
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.88244  0.88110  0.88260  0.88109  0.88232  0.88130  0.88282  0.88130
3995  0.88234  0.88232  0.88315  0.88215  0.88224  0.88256  0.88337  0.88235
3996  0.88368  0.88223  0.88359  0.88196  0.88357  0.88245  0.88381  0.88220
3997  0.88439  0.88355  0.88436  0.88308  0.88423  0.88378  0.88459  0.88329
3998  0.88416  0.88420  0.88446  0.88253  0.88405  0.88452  0.88466  0.88272

        ask_c
0     0.87779
1     0.87726
2     0.87750
3     0.87775
4     0.87801
...       ...
3994  0.88255
3995  0.88243
3996  0.88379
3997  0.88455
3998  0.88427

[3999 rows x 14 columns]
NZD_CAD loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
CAD_EUR Error
CAD_USD Error
CAD_GBP Error
                                time  volume   mid_o   mid_h   mid_l   mid_c  \
0     2020-09-11T00:00:00.000000000Z    3423  80.480  80.524  80.434  80.493
1     2020-09-11T01:00:00.000000000Z    2990  80.491  80.597  80.490  80.572
2     2020-09-11T02:00:00.000000000Z    1545  80.572  80.592  80.556  80.581
3     2020-09-11T03:00:00.000000000Z    1574  80.583  80.588  80.532  80.586
4     2020-09-11T04:00:00.000000000Z    1498  80.586  80.605  80.576  80.590
...                              ...     ...     ...     ...     ...     ...
3994  2021-05-05T10:00:00.000000000Z    2707  89.010  89.088  88.987  89.057
3995  2021-05-05T11:00:00.000000000Z    2115  89.054  89.103  89.014  89.081
3996  2021-05-05T12:00:00.000000000Z    4660  89.080  89.126  89.014  89.042
3997  2021-05-05T13:00:00.000000000Z    5291  89.043  89.048  88.908  88.986
3998  2021-05-05T14:00:00.000000000Z    6645  88.988  89.140  88.950  89.102

       bid_o   bid_h   bid_l   bid_c   ask_o   ask_h   ask_l   ask_c
0     80.469  80.515  80.422  80.485  80.490  80.536  80.443  80.501
1     80.482  80.587  80.481  80.563  80.500  80.607  80.498  80.582
2     80.562  80.584  80.547  80.572  80.582  80.601  80.566  80.590
3     80.573  80.579  80.523  80.577  80.593  80.596  80.541  80.596
4     80.576  80.597  80.567  80.581  80.596  80.614  80.583  80.598
...      ...     ...     ...     ...     ...     ...     ...     ...
3994  89.003  89.080  88.979  89.049  89.016  89.095  88.995  89.065
3995  89.046  89.095  89.007  89.073  89.062  89.111  89.021  89.089
3996  89.073  89.119  89.006  89.034  89.088  89.133  89.021  89.049
3997  89.036  89.040  88.901  88.974  89.050  89.055  88.916  88.999
3998  88.976  89.132  88.943  89.094  88.999  89.147  88.957  89.110

[3999 rows x 14 columns]
CAD_JPY loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     563  0.69018  0.69025  0.68986
1     2020-09-11T01:00:00.000000000Z     388  0.69006  0.69068  0.68987
2     2020-09-11T02:00:00.000000000Z     199  0.69059  0.69070  0.69050
3     2020-09-11T03:00:00.000000000Z     174  0.69050  0.69061  0.69034
4     2020-09-11T04:00:00.000000000Z     123  0.69060  0.69066  0.69052
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     541  0.74486  0.74502  0.74438
3995  2021-05-05T11:00:00.000000000Z     406  0.74441  0.74450  0.74373
3996  2021-05-05T12:00:00.000000000Z     752  0.74396  0.74464  0.74396
3997  2021-05-05T13:00:00.000000000Z    1122  0.74406  0.74446  0.74317
3998  2021-05-05T14:00:00.000000000Z    1317  0.74395  0.74530  0.74360

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.69005  0.69006  0.69013  0.68973  0.68993  0.69031  0.69037  0.68998
1     0.69062  0.68993  0.69056  0.68974  0.69051  0.69018  0.69080  0.69000
2     0.69054  0.69044  0.69058  0.69037  0.69042  0.69074  0.69082  0.69061
3     0.69057  0.69039  0.69050  0.69022  0.69046  0.69062  0.69072  0.69045
4     0.69064  0.69049  0.69056  0.69041  0.69054  0.69072  0.69077  0.69064
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.74446  0.74475  0.74492  0.74427  0.74435  0.74498  0.74513  0.74450
3995  0.74400  0.74431  0.74439  0.74362  0.74389  0.74451  0.74462  0.74384
3996  0.74404  0.74385  0.74454  0.74384  0.74394  0.74407  0.74475  0.74407
3997  0.74390  0.74396  0.74436  0.74305  0.74371  0.74416  0.74457  0.74329
3998  0.74503  0.74376  0.74518  0.74349  0.74492  0.74414  0.74541  0.74370

        ask_c
0     0.69017
1     0.69074
2     0.69067
3     0.69068
4     0.69075
...       ...
3994  0.74457
3995  0.74410
3996  0.74413
3997  0.74409
3998  0.74514

[3999 rows x 14 columns]
CAD_CHF loaded 3999 candles from 2020-09-11T00:00:00.000000000Z to 2021-05-05T14:00:00.000000000Z
CAD_NZD Error

In [16]:
pickle_off = open("CAD_CHF_H1.pkl","rb")
emp = pickle.load(pickle_off)
print(emp)

                                time  volume    mid_o    mid_h    mid_l  \
0     2020-09-11T00:00:00.000000000Z     563  0.69018  0.69025  0.68986
1     2020-09-11T01:00:00.000000000Z     388  0.69006  0.69068  0.68987
2     2020-09-11T02:00:00.000000000Z     199  0.69059  0.69070  0.69050
3     2020-09-11T03:00:00.000000000Z     174  0.69050  0.69061  0.69034
4     2020-09-11T04:00:00.000000000Z     123  0.69060  0.69066  0.69052
...                              ...     ...      ...      ...      ...
3994  2021-05-05T10:00:00.000000000Z     541  0.74486  0.74502  0.74438
3995  2021-05-05T11:00:00.000000000Z     406  0.74441  0.74450  0.74373
3996  2021-05-05T12:00:00.000000000Z     752  0.74396  0.74464  0.74396
3997  2021-05-05T13:00:00.000000000Z    1122  0.74406  0.74446  0.74317
3998  2021-05-05T14:00:00.000000000Z    1317  0.74395  0.74530  0.74360

        mid_c    bid_o    bid_h    bid_l    bid_c    ask_o    ask_h    ask_l  \
0     0.69005  0.69006  0.69013  0.68973  0.68993  0.69031  0.69037  0.68998
1     0.69062  0.68993  0.69056  0.68974  0.69051  0.69018  0.69080  0.69000
2     0.69054  0.69044  0.69058  0.69037  0.69042  0.69074  0.69082  0.69061
3     0.69057  0.69039  0.69050  0.69022  0.69046  0.69062  0.69072  0.69045
4     0.69064  0.69049  0.69056  0.69041  0.69054  0.69072  0.69077  0.69064
...       ...      ...      ...      ...      ...      ...      ...      ...
3994  0.74446  0.74475  0.74492  0.74427  0.74435  0.74498  0.74513  0.74450
3995  0.74400  0.74431  0.74439  0.74362  0.74389  0.74451  0.74462  0.74384
3996  0.74404  0.74385  0.74454  0.74384  0.74394  0.74407  0.74475  0.74407
3997  0.74390  0.74396  0.74436  0.74305  0.74371  0.74416  0.74457  0.74329
3998  0.74503  0.74376  0.74518  0.74349  0.74492  0.74414  0.74541  0.74370

        ask_c
0     0.69017
1     0.69074
2     0.69067
3     0.69068
4     0.69075
...       ...
3994  0.74457
3995  0.74410
3996  0.74413
3997  0.74409
3998  0.74514

[3999 rows x 14 columns]

In [23]:
df = pd.read_data(emp[0])

AttributeError: module 'pandas' has no attribute 'read_data'